module NumberDayCalendar exposing
    ( NumberDay
    , numberDayFromTime
    , numberDayToString
    )

import Dict exposing (Dict)
import Time


type NumberDay
    = One
    | Two
    | Three
    | Four
    | None


numberDayFromTime : Time.Zone -> Time.Posix -> NumberDay
numberDayFromTime zone posix =
    case Dict.get (dateKey zone posix) numberDayCalendar of
        Just numberDay ->
            numberDay

        Nothing ->
            None



-- For winter: gwynedd-square-letter-days-a.svg
-- For spring: gwynedd-square-letter-days-a-spring.svg


numberDayToString : NumberDay -> String
numberDayToString numberDay =
    case numberDay of
        One ->
            "Cycle Day 1"

        Two ->
            "Cycle Day 2"

        Three ->
            "Cycle Day 3"

        Four ->
            "Cycle Day 4"

        None ->
            "We're off today!"



-- UTILS


{-| This is the format of the keys for the letter day calendar dict.
-}
dateKey : Time.Zone -> Time.Posix -> String
dateKey zone posix =
    let
        day =
            Time.toDay zone posix
                |> String.fromInt
                |> String.padLeft 2 '0'

        month =
            Time.toMonth zone posix
                |> toMonthNumber

        year =
            Time.toYear zone posix
                |> String.fromInt
    in
    -- E.g., 2020-10-20
    year ++ "-" ++ month ++ "-" ++ day


toMonthNumber : Time.Month -> String
toMonthNumber month =
    case month of
        Time.Jan ->
            "01"

        Time.Feb ->
            "02"

        Time.Mar ->
            "03"

        Time.Apr ->
            "04"

        Time.May ->
            "05"

        Time.Jun ->
            "06"

        Time.Jul ->
            "07"

        Time.Aug ->
            "08"

        Time.Sep ->
            "09"

        Time.Oct ->
            "10"

        Time.Nov ->
            "11"

        Time.Dec ->
            "12"


{-| DON'T EDIT DIRECTLY: Auto generated by the parse\_number\_day\_calendar.rb
script.
-}
numberDayCalendar : Dict String NumberDay
numberDayCalendar =
    Dict.fromList
        [ ( "2022-08-30", One )
        , ( "2022-08-31", Two )
        , ( "2022-09-01", Three )
        , ( "2022-09-06", Four )
        , ( "2022-09-07", One )
        , ( "2022-09-08", Two )
        , ( "2022-09-09", Three )
        , ( "2022-09-12", Four )
        , ( "2022-09-13", One )
        , ( "2022-09-14", Two )
        , ( "2022-09-15", Three )
        , ( "2022-09-16", Four )
        , ( "2022-09-19", One )
        , ( "2022-09-20", Two )
        , ( "2022-09-21", Three )
        , ( "2022-09-22", Four )
        , ( "2022-09-23", One )
        , ( "2022-09-27", Two )
        , ( "2022-09-28", Three )
        , ( "2022-09-29", Four )
        , ( "2022-09-30", One )
        , ( "2022-10-03", Two )
        , ( "2022-10-04", Three )
        , ( "2022-10-06", Four )
        , ( "2022-10-07", One )
        , ( "2022-10-10", Two )
        , ( "2022-10-11", Three )
        , ( "2022-10-12", Four )
        , ( "2022-10-13", One )
        , ( "2022-10-14", Two )
        , ( "2022-10-17", Three )
        , ( "2022-10-18", Four )
        , ( "2022-10-19", One )
        , ( "2022-10-20", Two )
        , ( "2022-10-21", Three )
        , ( "2022-10-25", Four )
        , ( "2022-10-26", One )
        , ( "2022-10-27", Two )
        , ( "2022-10-28", Three )
        , ( "2022-10-31", Four )
        , ( "2022-11-01", One )
        , ( "2022-11-02", Two )
        , ( "2022-11-03", Three )
        , ( "2022-11-04", Four )
        , ( "2022-11-09", One )
        , ( "2022-11-10", Two )
        , ( "2022-11-11", Three )
        , ( "2022-11-14", Four )
        , ( "2022-11-15", One )
        , ( "2022-11-16", Two )
        , ( "2022-11-17", Three )
        , ( "2022-11-18", Four )
        , ( "2022-11-21", One )
        , ( "2022-11-22", Two )
        , ( "2022-11-28", Three )
        , ( "2022-11-29", Four )
        , ( "2022-11-30", One )
        , ( "2022-12-01", Two )
        , ( "2022-12-02", Three )
        , ( "2022-12-05", Four )
        , ( "2022-12-06", One )
        , ( "2022-12-07", Two )
        , ( "2022-12-08", Three )
        , ( "2022-12-09", Four )
        , ( "2022-12-12", One )
        , ( "2022-12-13", Two )
        , ( "2022-12-14", Three )
        , ( "2022-12-15", Four )
        , ( "2022-12-16", One )
        , ( "2022-12-19", Two )
        , ( "2022-12-20", Three )
        , ( "2022-12-21", Four )
        , ( "2022-12-22", One )
        , ( "2022-12-23", Two )
        , ( "2023-01-03", Three )
        , ( "2023-01-04", Four )
        , ( "2023-01-05", One )
        , ( "2023-01-06", Two )
        , ( "2023-01-09", Three )
        , ( "2023-01-10", Four )
        , ( "2023-01-11", One )
        , ( "2023-01-12", Two )
        , ( "2023-01-13", Three )
        , ( "2023-01-17", Four )
        , ( "2023-01-18", One )
        , ( "2023-01-19", Two )
        , ( "2023-01-20", Three )
        , ( "2023-01-23", Four )
        , ( "2023-01-24", One )
        , ( "2023-01-25", Two )
        , ( "2023-01-26", Three )
        , ( "2023-01-27", Four )
        , ( "2023-01-30", One )
        , ( "2023-01-31", Two )
        , ( "2023-02-01", Three )
        , ( "2023-02-02", Four )
        , ( "2023-02-03", One )
        , ( "2023-02-06", Two )
        , ( "2023-02-07", Three )
        , ( "2023-02-08", Four )
        , ( "2023-02-09", One )
        , ( "2023-02-10", Two )
        , ( "2023-02-13", Three )
        , ( "2023-02-14", Four )
        , ( "2023-02-15", One )
        , ( "2023-02-16", Two )
        , ( "2023-02-21", Three )
        , ( "2023-02-22", Four )
        , ( "2023-02-23", One )
        , ( "2023-02-24", Two )
        , ( "2023-02-27", Three )
        , ( "2023-02-28", Four )
        , ( "2023-03-01", One )
        , ( "2023-03-02", Two )
        , ( "2023-03-03", Three )
        , ( "2023-03-06", Four )
        , ( "2023-03-07", One )
        , ( "2023-03-08", Two )
        , ( "2023-03-09", Three )
        , ( "2023-03-10", Four )
        , ( "2023-03-13", One )
        , ( "2023-03-14", Two )
        , ( "2023-03-15", Three )
        , ( "2023-03-16", Four )
        , ( "2023-03-17", One )
        , ( "2023-03-20", Two )
        , ( "2023-03-21", Three )
        , ( "2023-03-22", Four )
        , ( "2023-03-23", One )
        , ( "2023-03-24", Two )
        , ( "2023-03-27", Three )
        , ( "2023-03-28", Four )
        , ( "2023-03-29", One )
        , ( "2023-03-30", Two )
        , ( "2023-03-31", Three )
        , ( "2023-04-10", Four )
        , ( "2023-04-11", One )
        , ( "2023-04-12", Two )
        , ( "2023-04-13", Three )
        , ( "2023-04-14", Four )
        , ( "2023-04-17", One )
        , ( "2023-04-18", Two )
        , ( "2023-04-19", Three )
        , ( "2023-04-20", Four )
        , ( "2023-04-24", One )
        , ( "2023-04-25", Two )
        , ( "2023-04-26", Three )
        , ( "2023-04-27", Four )
        , ( "2023-04-28", One )
        , ( "2023-05-01", Two )
        , ( "2023-05-02", Three )
        , ( "2023-05-03", Four )
        , ( "2023-05-04", One )
        , ( "2023-05-05", Two )
        , ( "2023-05-08", Three )
        , ( "2023-05-09", Four )
        , ( "2023-05-10", One )
        , ( "2023-05-11", Two )
        , ( "2023-05-12", Three )
        , ( "2023-05-15", Four )
        , ( "2023-05-17", One )
        , ( "2023-05-18", Two )
        , ( "2023-05-19", Three )
        , ( "2023-05-22", Four )
        , ( "2023-05-23", One )
        , ( "2023-05-24", Two )
        , ( "2023-05-25", Three )
        , ( "2023-05-26", Four )
        , ( "2023-05-30", One )
        , ( "2023-05-31", Two )
        , ( "2023-06-01", Three )
        , ( "2023-06-02", Four )
        , ( "2023-06-05", One )
        , ( "2023-06-06", Two )
        , ( "2023-06-07", Three )
        , ( "2023-06-08", Four )
        , ( "2023-06-09", One )
        , ( "2023-06-12", Two )
        , ( "2023-06-13", Three )
        , ( "2023-06-14", Four )
        ]
